config/routes.rb
Locomotive::Engine.routes.draw do

  # authentication
  devise_for :locomotive_account,
    class_name:   'Locomotive::Account',
    path:         '',
    path_prefix:  nil,
    failure_app:  'Locomotive::Devise::FailureApp',
    controllers:  { sessions: 'locomotive/sessions', passwords: 'locomotive/passwords' }

  devise_scope :locomotive_account do
    match '/'         => 'sessions#new'
    delete 'signout'  => 'sessions#destroy', as: :destroy_locomotive_session
  end

  root to: 'pages#index'

  resources :pages do
    put :sort, on: :member
    get :get_path, on: :collection
  end

  resources :snippets

  resources :sites

  resource :current_site, controller: 'current_site'

  resources :accounts

  resource :my_account, controller: 'my_account'

  resources :memberships

  resources :theme_assets do
    get :all, action: 'index', on: :collection, defaults: { all: true }
  end

  resources :translations

  resources :content_assets

  resources :content_types

  resources :content_entries, path: 'content_types/:slug/entries' do
    put :sort,    on: :collection
    get :export,  on: :collection
  end

  # installation guide
  match '/installation'       => 'installation#show', defaults: { step: 1 }, as: :installation
  match '/installation/:step' => 'installation#show', as: :installation_step

end

Rails.application.routes.draw do

  # API
  namespace :locomotive, module: 'locomotive' do
    namespace :api do

      resources :tokens, only: [:create, :destroy]

      resource  :current_site, controller: 'current_site', only: [:show, :update, :destroy]

      resources :memberships, only: [:index, :show, :create, :update, :destroy]

      resource  :my_account, controller: 'my_account', only: :show

      resources :accounts, only: [:index, :show, :create, :destroy]

      with_options only: [:index, :show, :create, :update, :destroy] do |api|

        api.resources :sites

        api.resources :pages

        api.resources :snippets

        api.resources :content_types

        api.resources :content_entries, path: 'content_types/:slug/entries'

        api.resources :theme_assets

        api.resources :translations

        api.resources :content_assets
      end
    end
  end

  # sitemap
  match '/sitemap.xml'  => 'locomotive/public/sitemaps#show', format: 'xml'

  # robots.txt
  match '/robots.txt'   => 'locomotive/public/robots#show', format: 'txt'

  # public content entry submissions
  resources :locomotive_entry_submissions, controller: 'locomotive/public/content_entries', path: 'entry_submissions/:slug'

  # magic urls
  match '/_admin'               => 'locomotive/public/pages#show_toolbar'
  match ':locale/_admin'        => 'locomotive/public/pages#show_toolbar', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match ':locale/*path/_admin'  => 'locomotive/public/pages#show_toolbar', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match '*path/_admin'          => 'locomotive/public/pages#show_toolbar'

  match '/_edit'                => 'locomotive/public/pages#edit'
  match ':locale/_edit'         => 'locomotive/public/pages#edit', page_path: 'index', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match ':locale/*path/_edit'   => 'locomotive/public/pages#edit', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match '*path/_edit'           => 'locomotive/public/pages#edit'

  root to:                      'locomotive/public/pages#show'
  match ':locale'               => 'locomotive/public/pages#show', page_path: 'index', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match ':locale/*path'         => 'locomotive/public/pages#show', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match '*path'                 => 'locomotive/public/pages#show'
end

app/models/locomotive/ability.rb
module Locomotive
  class Ability
    include CanCan::Ability

    ROLES = %w(admin designer author)

    def initialize(account, site)
      @account, @site = account, site

      alias_action :index, :show, :edit, :update, to: :touch

      if @site
        @membership = @site.memberships.where(account_id: @account.id).first
      elsif @account.admin?
        @membership = Membership.new(account: @account, role: 'admin')
      end

      return false if @membership.nil?

      if @membership.admin?
        setup_admin_permissions!
      else
        setup_default_permissions!

        setup_designer_permissions! if @membership.designer?

        setup_author_permissions!  if @membership.author?
      end
    end

    def setup_default_permissions!
      cannot :manage, :all
    end

    def setup_author_permissions!
      can :touch, ThemeAsset

      can [:read, :create, :update], Page
      cannot :destroy, Page
      cannot :customize, Page

      can :manage, [ContentEntry, ContentAsset, Translation]

      can :touch, Site, _id: @site._id

      can :read, ContentType
    end

    def setup_designer_permissions!
      can :manage, Page

      can :manage, ContentEntry

      can :manage, ContentType

      can :manage, Snippet

      can :manage, ThemeAsset

      can :manage, ContentAsset

      can :manage, Translation

      can :manage, Site, _id: @site._id

      can :point, Site

      cannot :create, Site

      can :manage, Membership

      cannot :grant_admin, Membership

      cannot [:update, :destroy], Membership do |membership|
        @membership.account_id == membership.account_id || # can not edit myself
        membership.admin? # can not modify an administrator
      end
    end

    def setup_admin_permissions!
      can :manage, :all

      cannot [:update, :destroy], Membership do |membership|
        @membership.account_id == membership.account_id # can not edit myself
      end
    end
  end
end

app/models/locomotive/account.rb
module Locomotive
  class Account

    include Locomotive::Mongoid::Document

    devise *Locomotive.config.devise_modules

    ## devise fields (need to be declared since 2.x) ##
    field :remember_created_at,     type: Time
    field :email,                   type: String, default: ''
    field :encrypted_password,      type: String, default: ''
    field :authentication_token,    type: String
    field :reset_password_token,    type: String
    field :reset_password_sent_at,  type: Time
    field :password_salt,           type: String
    field :sign_in_count,           type: Integer, default: 0
    field :current_sign_in_at,      type: Time
    field :last_sign_in_at,         type: Time
    field :current_sign_in_ip,      type: String
    field :last_sign_in_ip,         type: String

    ## attributes ##
    field :name
    field :locale, default: Locomotive.config.default_locale.to_s or 'en'

    ## validations ##
    validates_presence_of :name

    ## associations ##

    ## callbacks ##
    before_destroy :remove_memberships!

    ## scopes ##
    scope :ordered, order_by(name: :asc)

    ## indexes ##
    index({ email: 1 }, { unique: true, background: true })

    ## methods ##

    def sites
      @sites ||= Site.where('memberships.account_id' => self._id)
    end

    # Tell if the account has admin privileges or not.
    # Actually, an account is considered as an admin if
    # it owns at least one admin membership in all its sites.
    #
    # @return [ Boolean ] True if admin
    #
    def admin?
      Site.where(memberships: { '$elemMatch' => { account_id: self._id, role: :admin } }).count > 0
    end

    # Create the API token which will be passed to all the requests to the Locomotive API.
    # It requires the credentials of an account with admin role.
    # If an error occurs (invalid account, ...etc), this method raises an exception that has
    # to be caught somewhere.
    #
    # @param [ Site ] site The site where the authentication request is made
    # @param [ String ] email The email of the account
    # @param [ String ] password The password of the account
    #
    # @return [ String ] The API token
    #
    def self.create_api_token(site, email, password)
      raise 'The request must contain the user email and password.' if email.blank? or password.blank?

      account = self.where(email: email.downcase).first

      raise 'Invalid email or password.' if account.nil?

      account.ensure_authentication_token!

      if not account.valid_password?(password) # TODO: check admin roles
        raise 'Invalid email or password.'
      end

      account.authentication_token
    end

    # Logout the user responding to the token passed in parameter from the API.
    # An exception is raised if no account corresponds to the token.
    #
    # @param [ String ] token The API token created by the create_api_token method.
    #
    # @return [ String ] The API token
    #
    def self.invalidate_api_token(token)
      account = self.where(authentication_token: token).first

      raise 'Invalid token.' if account.nil?

      account.reset_authentication_token!

      token
    end

    def devise_mailer
      Locomotive::DeviseMailer
    end

    protected

    def password_required?
      !persisted? || !password.blank? || !password_confirmation.blank?
    end

    def remove_memberships!
      self.sites.each do |site|
        membership = site.memberships.where(account_id: self._id).first

        if site.admin_memberships.size == 1 && membership.admin?
          raise ::I18n.t('errors.messages.needs_admin_account')
        else
          membership.destroy
        end
      end
    end

  end
end

app/models/locomotive/content_asset.rb
module Locomotive
  class ContentAsset

    include Locomotive::Mongoid::Document

    ## extensions ##
    include Extensions::Asset::Types
    include Extensions::Asset::Vignette

    ## fields ##
    field :content_type,  type: String
    field :width,         type: Integer
    field :height,        type: Integer
    field :size,          type: Integer
    field :position,      type: Integer, default: 0

    ## associations ##
    belongs_to :site, class_name: 'Locomotive::Site'

    ## validations ##
    validates_presence_of :source

    ## behaviours ##
    mount_uploader :source, ContentAssetUploader, mount_on: :source_filename

    ## methods ##

    alias :name :source_filename

    def extname
      return nil unless self.source?
      File.extname(self.source_filename).gsub(/^\./, '')
    end

    def to_liquid
      { url: self.source.url }.merge(self.attributes).stringify_keys
    end

  end
end

app/models/locomotive/content_entry.rb
module Locomotive
  class ContentEntry

    include Locomotive::Mongoid::Document

    ## extensions ##
    include ::CustomFields::Target
    include Extensions::Shared::Seo
    include Extensions::ContentEntry::Csv

    ## fields ##
    field :_slug
    field :_label_field_name
    field :_position,         type: Integer, default: 0
    field :_visible,          type: Boolean, default: true

    ## validations ##
    validates :_slug, presence: true, uniqueness: { scope: :content_type_id }

    ## associations ##
    belongs_to  :site,          class_name: 'Locomotive::Site'
    belongs_to  :content_type,  class_name: 'Locomotive::ContentType', inverse_of: :entries, custom_fields_parent_klass: true

    ## callbacks ##
    before_validation :set_slug
    before_save       :set_site
    before_save       :set_visibility
    before_save       :set_label_field_name
    before_create     :add_to_list_bottom
    after_create      :send_notifications

    ## named scopes ##
    scope :visible, where(_visible: true)
    scope :latest_updated, order_by(updated_at: :desc).limit(Locomotive.config.ui[:latest_entries_nb])

    ## methods ##

    alias :visible? :_visible?
    alias :_permalink :_slug
    alias :_permalink= :_slug=

    # Any content entry owns a label property which is used in the back-office UI
    # to represent it. The field used as the label is defined within the parent content type.
    #
    # @param [ Object ] (optional) The content type to avoid to run another MongoDB and useless query.
    #
    # @return [ String ] The "label" of the content entry
    #
    def _label(type = nil)
      value = if self._label_field_name
        self.send(self._label_field_name.to_sym)
      else
        self.send((type || self.content_type).label_field_name.to_sym)
      end

      value.respond_to?(:to_label) ? value.to_label : value.to_s
    end

    alias :to_label :_label

    # Tell if the content entry has been translated or not.
    # It just checks if the field used for the label has been translated.
    #
    # @return [ Boolean ] True if translated, false otherwise
    #
    def translated?
      if self.respond_to?(:"#{self._label_field_name}_translations")
        self.send(:"#{self._label_field_name}_translations").key?(::Mongoid::Fields::I18n.locale.to_s) #rescue false
      else
        true
      end
    end

    # Return the locales the content entry has been translated to.
    #
    # @return [ Array ] The list of locales. Nil if not localized
    #
    def translated_in
      if self.respond_to?(:"#{self._label_field_name}_translations")
        self.send(:"#{self._label_field_name}_translations").keys
      else
        nil
      end
    end

    # Return the next content entry based on the order defined in the parent content type.
    #
    # @param [ Object ] The next content entry or nil if not found
    #
    def next
      next_or_previous :gt
    end

    # Return the previous content entry based on the order defined in the parent content type.
    #
    # @param [ Object ] The previous content entry or nil if not found
    #
    def previous
      next_or_previous :lt
    end

    # Find a content entry by its permalink
    #
    # @param [ String ] The permalink
    #
    # @return [ Object ] The content entry matching the permalink or nil if not found
    #
    def self.find_by_permalink(permalink)
      self.where(_slug: permalink).first
    end

    # Sort the content entries from an ordered array of content entry ids.
    # Their new positions are persisted.
    #
    # @param [ Array ] The ordered array of ids
    #
    def self.sort_entries!(ids)
      list = self.any_in(_id: ids.map { |id| Moped::BSON::ObjectId.from_string(id.to_s) }).to_a
      ids.each_with_index do |id, position|
        if entry = list.detect { |e| e._id.to_s == id.to_s }
          entry.update_attributes _position: position
        end
      end
    end

    # All the content entries no matter the content type they belong to
    # share the same presenter class.
    #
    # @param [ Class ] The content entry presenter class
    #
    def self.presenter_class
      Locomotive::ContentEntryPresenter
    end

    # All the content entries no matter the content type they belong to
    # share the same liquid drop class.
    #
    # @param [ Class ] The liquid drop class
    #
    def self.drop_class
      Locomotive::Liquid::Drops::ContentEntry
    end

    protected

    # Retrieve the next or the previous entry following the order
    # defined in the parent content type.
    #
    # @param [ Symbol ] :gt for the next element, :lt for the previous element
    #
    # @return [ Object ] The next or previous content entry or nil if none
    #
    def next_or_previous(matcher = :gt)
      order_by  = self.content_type.order_by_definition(matcher == :lt)
      criterion = self.content_type.order_by_attribute.to_sym.send(matcher)
      value     = self.send(self.content_type.order_by_attribute.to_sym)

      self.class.where(criterion => value).order_by(:order_by.asc).limit(1).first
    end

    # Sets the slug of the instance by using the value of the highlighted field
    # (if available). If a sibling content instance has the same permalink then a
    # unique one will be generated
    def set_slug
      self._slug = self._label.dup if self._slug.blank? && self._label.present?

      if self._slug.present?
        self._slug.permalink!
        self._slug = self.next_unique_slug if self.slug_already_taken?
      end
    end

    # Return the next available unique slug as a string
    def next_unique_slug
      slug        = self._slug.gsub(/-\d+$/, '')
      similar_slugs   = self.class.where(:_id.ne => self._id, _slug: /^#{slug}-?\d*$/i)
      next_number = similar_slugs.map {|s| s._slug.scan(/-(\d+)$/).flatten.last.to_i }.max + 1
      [slug, next_number].join('-')
    end

    def slug_already_taken?
      self.class.where(:_id.ne => self._id, _slug: self._slug).any?
    end

    def set_site
      self.site ||= self.content_type.site
    end

    def set_visibility
      if self.respond_to?(:visible)
        self.visible  = true if self.visible.nil?
        self._visible = self.visible
        return
      end
    end

    def set_label_field_name
      self._label_field_name = self.content_type.label_field_name
    end

    def add_to_list_bottom
      self._position = self.class.max(:_position).to_i + 1
    end

    def send_notifications
      return if !self.content_type.public_submission_enabled? || self.content_type.public_submission_accounts.blank?

      self.site.accounts.each do |account|
        next unless self.content_type.public_submission_accounts.map(&:to_s).include?(account._id.to_s)

        Locomotive::Notifications.new_content_entry(account, self).deliver
      end
    end

  end
end

app/models/locomotive/editable_long_text.rb
module Locomotive
  class EditableLongText < EditableShortText

  end
end

app/models/locomotive/extensions/asset/vignette.rb
module Locomotive
  module Extensions
    module Asset
      module Vignette

        def vignette_url
          if self.image?
            if self.width < 85 && self.height < 85
              self.source.url
            else
              Locomotive::Dragonfly.resize_url(self.source, '85x85#')
            end
          end
        end

      end
    end
  end
end

app/views/locomotive/content_entries/_form.html.haml
- content_for :head do
  = render '/locomotive/content_assets/picker'

- content_for :backbone_view_data do
  :plain
    content_entry: #{escape_json to_json(@content_entry)},
    content_type: #{escape_json to_json(@content_type)}

= f.inputs name: :attributes do
  - @content_type.ordered_entries_custom_fields.each_with_index do |field, index|
    = render "locomotive/custom_fields/types/#{field.type}",
      f:            f,
      name:         field.name.to_sym,
      field:        field,
      highlighted:  field._id == @content_type.label_field_id

= f.inputs name: :advanced_options, class: "inputs foldable #{'folded' if inputs_folded?(@content_entry)}" do

  = f.input :_slug
  = f.input :seo_title
  = f.input :meta_keywords
  = f.input :meta_description

app/views/locomotive/content_entries/_list.html.haml
- if entries.empty?
  %p.no-items!= t('.no_items', url: new_content_entry_url(content_type.slug))
- else
  %ul{ id: 'entries-list', class: "#{'list' unless content_type.groupable?} #{'sortable' if content_type.order_manually?}", :'data-url' => sort_content_entries_url(content_type.slug, :json) }
    - entries.each do |entry|
      %li.item{ id: "entry-#{entry._id}" }
        %span.handle

        %strong= link_to entry_label(content_type, entry), edit_content_entry_url(content_type.slug, entry)

        - unless entry.translated?
          %span.untranslated= t('locomotive.shared.list.untranslated')
        .more
          %span
            != t('locomotive.content_entries.index.updated_at')
          = l entry.updated_at, format: :short rescue 'n/a'

          = link_to_icon :trash, content_entry_url(content_type.slug, entry), title: t('locomotive.buttons.delete'), class: 'remove', data: { confirm: t('locomotive.messages.confirm') }, method: :delete

  - if entries.respond_to?(:current_page)
    = paginate entries, namespace: 'locomotive'

app/views/locomotive/content_entries/edit.html.haml
- title t('.title', type: @content_type.name.capitalize)

- content_for :submenu do
  = render 'locomotive/shared/menu/contents'

- content_for :actions do
  = render 'locomotive/shared/actions/contents'

- content_for :buttons do
  - if can?(:manage, Locomotive::ContentType)
    = local_action_button t('locomotive.content_entries.index.edit'), edit_content_type_url(@content_type), icon: 'icon-pencil'

  = local_action_button t('locomotive.content_entries.index.new'), new_content_entry_url(@content_type.slug), icon: 'icon-plus'

%p= @content_type.description

= semantic_form_for @content_entry, as: :content_entry, url: content_entry_url(@content_type.slug, @content_entry), html: { multipart: true } do |form|

  = render 'form', f: form

  = render 'locomotive/shared/form_actions', back_url: content_entries_url(@content_type.slug), button_label: :update

- content_for :foot do
  = render_has_many_forms

app/views/locomotive/content_entries/index.html.haml
- title t('.title', type: @content_type.name.capitalize)

- content_for :actions do
  = render 'locomotive/shared/actions/contents'

- content_for :buttons do
  - if can?(:manage, Locomotive::ContentType)
    = local_action_button :edit, edit_content_type_url(@content_type), icon: 'icon-pencil'

  = local_action_button :export, export_content_entries_url(@content_type.slug, :csv), icon: 'icon-download'

  = local_action_button :new, new_content_entry_url(@content_type.slug), icon: 'icon-plus'

- if @content_type.description.present?
  %p= @content_type.description

- if @content_type.groupable?
  - @content_entries.each do |group|
    .box
      %h3= group[:name] || t('.category_noname')
      .inner
        = render 'list', content_type: @content_type, entries: group[:entries]
- else
  = render 'list', content_type: @content_type, entries: @content_entries

- # Note: submenu has to be here in order to have the previous entries correctly rendered since we do not return
- #       all the attributes of the content types in the following code (causing stale documents)
- content_for :submenu do
  = render 'locomotive/shared/menu/contents'

- if can?(:manage, Locomotive::ContentType)
  #local-actions-bottom-bar
    %p.tleft
      = link_to t('.destroy'), content_type_url(@content_type), data: { confirm: t('locomotive.messages.confirm') }, method: :delete, class: 'button remove'

app/views/locomotive/content_entries/new.html.haml
- title t('.title', type: @content_type.name.capitalize)

- content_for :submenu do
  = render 'locomotive/shared/menu/contents'

- content_for :actions do
  = render 'locomotive/shared/actions/contents'

- if can?(:manage, Locomotive::ContentType)
  - content_for :buttons do
    = local_action_button t('locomotive.content_entries.index.edit'), edit_content_type_url(@content_type), icon: 'icon-pencil'

%p= @content_type.description

= semantic_form_for @content_entry, as: :content_entry, url: content_entries_url(@content_type.slug), html: { multipart: true } do |form|

  = render 'form', f: form

  = render 'locomotive/shared/form_actions', back_url: content_entries_url(@content_type.slug), button_label: :create

- content_for :foot do
  = render_has_many_forms